# This file contains Terraform import blocks
# Generated by tfimport-cli
# Review and apply with: terraform apply -import

import {
  to = aws_cloudwatch_log_group.flow_log
  id = "/aws/flow-log/vpc/vpc-050ca050768d3f328/ex-tfimport-external-20260531201513977300000006"
}
import {
  to = aws_directory_service_directory.this
  id = "d-906671849a"
}
import {
  to = aws_iam_role.flow_log_cloudwatch
  id = "ex-tfimport-external-20260531201512165800000002"
}
import {
  to = aws_iam_role_policy.flow_log_cloudwatch
  id = "ex-tfimport-external-20260531201512165800000002:ex-tfimport-external-20260531201514898900000007"
}
import {
  to = aws_network_interface.this
  id = "eni-005d233dc31dad981"
}
import {
  to = aws_network_interface_sg_attachment.sg_attachment
  id = "eni-005d233dc31dad981_sg-0be082a7b2e1f03f3"
}
import {
  to = aws_security_group.example_sg
  id = "sg-0be082a7b2e1f03f3"
}
import {
  to = aws_security_group.rds
  id = "sg-0e77064c8db9a81bc"
}
import {
  to = aws_security_group_rule.allow_all_outbound
  id = "sg-0be082a7b2e1f03f3_egress_-1_0_0_0.0.0.0/0"
}
import {
  to = aws_security_group_rule.allow_http
  id = "sg-0be082a7b2e1f03f3_ingress_tcp_80_80_10.0.0.0/8_172.16.0.0/12_192.168.0.0/16"
}
import {
  to = aws_security_group_rule.allow_https
  id = "sg-0be082a7b2e1f03f3_ingress_tcp_443_443_10.0.0.0/8"
}
import {
  to = aws_security_group_rule.allow_ssh_from_vpc
  id = "sg-0be082a7b2e1f03f3_ingress_tcp_22_22_10.0.0.0/8_172.16.0.0/12_192.168.0.0/16"
}
import {
  to = module.ec2_instance["one"].aws_iam_instance_profile.this[0]
  id = "ex-tfimport-instance-one-20260531201512511500000005"
}
import {
  to = module.ec2_instance["one"].aws_iam_role.this[0]
  id = "ex-tfimport-instance-one-20260531201512070500000001"
}
import {
  to = module.ec2_instance["one"].aws_iam_role_policy_attachment.this["AmazonSSMManagedInstanceCore"]
  id = "ex-tfimport-instance-one-20260531201512070500000001/arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}
import {
  to = module.ec2_instance["one"].aws_instance.this[0]
  id = "i-0b4c20304b0eb0e8a"
}
import {
  to = module.ec2_instance["one"].aws_security_group.this[0]
  id = "sg-04dab12a6ae0c0a6a"
}
import {
  to = module.ec2_instance["one"].aws_vpc_security_group_egress_rule.this["ipv4_default"]
  id = "sgr-057500272ea4c7f26"
}
import {
  to = module.ec2_instance["one"].aws_vpc_security_group_egress_rule.this["ipv6_default"]
  id = "sgr-02d2ad03f5b1d1deb"
}
import {
  to = module.flow_log_cloudwatch_external.aws_flow_log.this[0]
  id = "fl-08b4b1ef8ce18f99b"
}
import {
  to = module.fsx_windows.aws_cloudwatch_log_group.this[0]
  id = "/aws/fsx/ex-tfimport-windows-20260531195744427100000001"
}
import {
  to = module.fsx_windows.aws_fsx_windows_file_system.this[0]
  id = "fs-033c4fdcfd27a909a"
}
import {
  to = module.fsx_windows.aws_security_group.this[0]
  id = "sg-07e2915dab4f78ca2"
}
import {
  to = module.fsx_windows.aws_vpc_security_group_egress_rule.this["out"]
  id = "sgr-082a13dca163b2d5d"
}
import {
  to = module.fsx_windows.aws_vpc_security_group_ingress_rule.this["in"]
  id = "sgr-0e39cba67fa06b79c"
}
import {
  to = module.iam_role_github_oidc.aws_iam_role.this[0]
  id = "ex-tfimport-20260531195744429500000003"
}
import {
  to = module.iam_role_github_oidc.aws_iam_role_policy_attachment.this["S3ReadOnly"]
  id = "ex-tfimport-20260531195744429500000003/arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
}
import {
  to = module.iam_role_inline_policy.aws_iam_instance_profile.this[0]
  id = "ex-tfimport-inline-policy-20260531195744649000000004"
}
import {
  to = module.iam_role_inline_policy.aws_iam_role.this[0]
  id = "ex-tfimport-inline-policy-20260531195744428900000002"
}
import {
  to = module.iam_role_inline_policy.aws_iam_role_policy.inline[0]
  id = "ex-tfimport-inline-policy-20260531195744428900000002:ex-tfimport-inline-policy-20260531195744649100000005"
}
import {
  to = module.kms.aws_kms_alias.this["mycompany/ebs"]
  id = "alias/mycompany/ebs"
}
import {
  to = module.kms.aws_kms_key.this[0]
  id = "22b836b8-f170-40f0-94cf-801e7fc46c50"
}
import {
  to = module.security_group.aws_security_group.this_name_prefix[0]
  id = "sg-0e917ad51c41e1de5"
}
import {
  to = module.security_group.aws_security_group_rule.ingress_rules[0]
  id = "sg-0e917ad51c41e1de5_ingress_tcp_80_80_0.0.0.0/0"
}
import {
  to = module.security_group.aws_security_group_rule.ingress_rules[1]
  id = "sg-0e917ad51c41e1de5_ingress_icmp_-1_-1_0.0.0.0/0"
}
import {
  to = module.vote_service_sg.aws_security_group.this_name_prefix[0]
  id = "sg-0068397675201af20"
}
import {
  to = module.vote_service_sg.aws_security_group_rule.ingress_rules[0]
  id = "sg-0068397675201af20_ingress_tcp_443_443_10.10.0.0/16"
}
import {
  to = module.vote_service_sg.aws_security_group_rule.ingress_with_cidr_blocks[0]
  id = "sg-0068397675201af20_ingress_tcp_8080_8090_10.10.0.0/16"
}
import {
  to = module.vote_service_sg.aws_security_group_rule.ingress_with_cidr_blocks[1]
  id = "sg-0068397675201af20_ingress_tcp_5432_5432_0.0.0.0/0"
}
import {
  to = module.vpc.aws_customer_gateway.this["IP1"]
  id = "cgw-07c7f0abd43ac03b0"
}
import {
  to = module.vpc.aws_customer_gateway.this["IP2"]
  id = "cgw-091fc6354c1690320"
}
import {
  to = module.vpc.aws_customer_gateway.this["IP3"]
  id = "cgw-0f04017c2002a5093"
}
import {
  to = module.vpc.aws_eip.nat[0]
  id = "eipalloc-07c955aed8d096a8b"
}
import {
  to = module.vpc.aws_elasticache_subnet_group.elasticache[0]
  id = "ex-tfimport"
}
import {
  to = module.vpc.aws_internet_gateway.this[0]
  id = "igw-03ac7874ca0a54989"
}
import {
  to = module.vpc.aws_nat_gateway.this[0]
  id = "nat-0129b13192640722f"
}
import {
  to = module.vpc.aws_redshift_subnet_group.redshift[0]
  id = "ex-tfimport"
}
import {
  to = module.vpc.aws_route.private_nat_gateway[0]
  id = "rtb-0c5eaaafc92856c35_0.0.0.0/0"
}
import {
  to = module.vpc.aws_route.public_internet_gateway[0]
  id = "rtb-0e47b0cfded047626_0.0.0.0/0"
}
import {
  to = module.vpc.aws_route_table.intra[0]
  id = "rtb-003da34a3260be7f6"
}
import {
  to = module.vpc.aws_route_table.private[0]
  id = "rtb-0c5eaaafc92856c35"
}
import {
  to = module.vpc.aws_route_table.public[0]
  id = "rtb-0e47b0cfded047626"
}
import {
  to = module.vpc.aws_route_table_association.database[0]
  id = "subnet-094e5a6cc7ab6c87b/rtb-0c5eaaafc92856c35"
}
import {
  to = module.vpc.aws_route_table_association.database[1]
  id = "subnet-017a91350a5e34c79/rtb-0c5eaaafc92856c35"
}
import {
  to = module.vpc.aws_route_table_association.database[2]
  id = "subnet-012e65040b3a32141/rtb-0c5eaaafc92856c35"
}
import {
  to = module.vpc.aws_route_table_association.elasticache[0]
  id = "subnet-0c948de543578e06a/rtb-0c5eaaafc92856c35"
}
import {
  to = module.vpc.aws_route_table_association.elasticache[1]
  id = "subnet-07e1262fb2dfdc48b/rtb-0c5eaaafc92856c35"
}
import {
  to = module.vpc.aws_route_table_association.elasticache[2]
  id = "subnet-0b6056c0cdbfc187f/rtb-0c5eaaafc92856c35"
}
import {
  to = module.vpc.aws_route_table_association.intra[0]
  id = "subnet-0508ffe5e7b3799d8/rtb-003da34a3260be7f6"
}
import {
  to = module.vpc.aws_route_table_association.intra[1]
  id = "subnet-08b02559f2a8e0cb9/rtb-003da34a3260be7f6"
}
import {
  to = module.vpc.aws_route_table_association.intra[2]
  id = "subnet-0400d438d7641a803/rtb-003da34a3260be7f6"
}
import {
  to = module.vpc.aws_route_table_association.private[0]
  id = "subnet-0d748533d7ab1f1e4/rtb-0c5eaaafc92856c35"
}
import {
  to = module.vpc.aws_route_table_association.private[1]
  id = "subnet-076889951a7b6cc75/rtb-0c5eaaafc92856c35"
}
import {
  to = module.vpc.aws_route_table_association.private[2]
  id = "subnet-067859c08d8129ff7/rtb-0c5eaaafc92856c35"
}
import {
  to = module.vpc.aws_route_table_association.public[0]
  id = "subnet-0a8f599b387c0a8dd/rtb-0e47b0cfded047626"
}
import {
  to = module.vpc.aws_route_table_association.public[1]
  id = "subnet-021af2f896330e4b9/rtb-0e47b0cfded047626"
}
import {
  to = module.vpc.aws_route_table_association.public[2]
  id = "subnet-0f3583268c8f6e9be/rtb-0e47b0cfded047626"
}
import {
  to = module.vpc.aws_route_table_association.redshift[0]
  id = "subnet-088be88401959cd2c/rtb-0c5eaaafc92856c35"
}
import {
  to = module.vpc.aws_route_table_association.redshift[1]
  id = "subnet-013c6965e2ee03265/rtb-0c5eaaafc92856c35"
}
import {
  to = module.vpc.aws_route_table_association.redshift[2]
  id = "subnet-02a6a1b6db829eef6/rtb-0c5eaaafc92856c35"
}
import {
  to = module.vpc.aws_subnet.database[0]
  id = "subnet-094e5a6cc7ab6c87b"
}
import {
  to = module.vpc.aws_subnet.database[1]
  id = "subnet-017a91350a5e34c79"
}
import {
  to = module.vpc.aws_subnet.database[2]
  id = "subnet-012e65040b3a32141"
}
import {
  to = module.vpc.aws_subnet.elasticache[0]
  id = "subnet-0c948de543578e06a"
}
import {
  to = module.vpc.aws_subnet.elasticache[1]
  id = "subnet-07e1262fb2dfdc48b"
}
import {
  to = module.vpc.aws_subnet.elasticache[2]
  id = "subnet-0b6056c0cdbfc187f"
}
import {
  to = module.vpc.aws_subnet.intra[0]
  id = "subnet-0508ffe5e7b3799d8"
}
import {
  to = module.vpc.aws_subnet.intra[1]
  id = "subnet-08b02559f2a8e0cb9"
}
import {
  to = module.vpc.aws_subnet.intra[2]
  id = "subnet-0400d438d7641a803"
}
import {
  to = module.vpc.aws_subnet.private[0]
  id = "subnet-0d748533d7ab1f1e4"
}
import {
  to = module.vpc.aws_subnet.private[1]
  id = "subnet-076889951a7b6cc75"
}
import {
  to = module.vpc.aws_subnet.private[2]
  id = "subnet-067859c08d8129ff7"
}
import {
  to = module.vpc.aws_subnet.public[0]
  id = "subnet-0a8f599b387c0a8dd"
}
import {
  to = module.vpc.aws_subnet.public[1]
  id = "subnet-021af2f896330e4b9"
}
import {
  to = module.vpc.aws_subnet.public[2]
  id = "subnet-0f3583268c8f6e9be"
}
import {
  to = module.vpc.aws_subnet.redshift[0]
  id = "subnet-088be88401959cd2c"
}
import {
  to = module.vpc.aws_subnet.redshift[1]
  id = "subnet-013c6965e2ee03265"
}
import {
  to = module.vpc.aws_subnet.redshift[2]
  id = "subnet-02a6a1b6db829eef6"
}
import {
  to = module.vpc.aws_vpc.this[0]
  id = "vpc-050ca050768d3f328"
}
import {
  to = module.vpc.aws_vpc_dhcp_options.this[0]
  id = "dopt-022afe0607543188a"
}
import {
  to = module.vpc.aws_vpc_dhcp_options_association.this[0]
  id = "vpc-050ca050768d3f328"
}
import {
  to = module.vpc.aws_vpn_gateway.this[0]
  id = "vgw-092f0b6e9662ad911"
}
import {
  to = module.vpc_endpoints.aws_security_group.this[0]
  id = "sg-09618af76e54f2a26"
}
import {
  to = module.vpc_endpoints.aws_security_group_rule.this["ingress_https"]
  id = "sg-09618af76e54f2a26_ingress_tcp_443_443_10.0.0.0/16"
}
import {
  to = module.vpc_endpoints.aws_vpc_endpoint.this["dynamodb"]
  id = "vpce-0af4a19843dde7fe5"
}
import {
  to = module.vpc_endpoints.aws_vpc_endpoint.this["ecr_api"]
  id = "vpce-06eea54d4f36dd0ab"
}
import {
  to = module.vpc_endpoints.aws_vpc_endpoint.this["ecr_dkr"]
  id = "vpce-02734d80622668198"
}
import {
  to = module.vpc_endpoints.aws_vpc_endpoint.this["ecs"]
  id = "vpce-067c3903fef0c2a2e"
}
import {
  to = module.vpc_endpoints.aws_vpc_endpoint.this["rds"]
  id = "vpce-05d4a467dc736e0f8"
}
import {
  to = module.vpc_endpoints.aws_vpc_endpoint.this["s3"]
  id = "vpce-03f50dc7b56547461"
}
