package pkg

import (
	"fmt"
	"sort"
	"strings"
)

// GenerateImportBlock creates a formatted Terraform import block
func GenerateImportBlock(resource Resource, importID string) *ImportBlock {
	return &ImportBlock{
		To: resource.Address,
		ID: importID,
	}
}

// FormatImportBlock formats an import block as Terraform code
func FormatImportBlock(block *ImportBlock) string {
	return fmt.Sprintf("import {\n  to = %s\n  id = %q\n}\n", block.To, block.ID)
}

// GenerateImportBlocksFromResources generates import blocks for multiple resources
func GenerateImportBlocksFromResources(resources []Resource) ([]ImportBlock, []SkippedResourceInfo) {
	var blocks []ImportBlock
	var skipped []SkippedResourceInfo

	for _, res := range resources {
		// Check if resource type is supported
		if !IsSupportedAWSResource(res.Type) {
			skipped = append(skipped, SkippedResourceInfo{
				Address: res.Address,
				Type:    res.Type,
				Reason:  fmt.Sprintf("resource type not supported: %s", res.Type),
			})
			continue
		}

		// Generate import ID
		importID, err := GetImportID(res)
		if err != nil {
			skipped = append(skipped, SkippedResourceInfo{
				Address: res.Address,
				Type:    res.Type,
				Reason:  fmt.Sprintf("failed to generate import ID: %v", err),
			})
			continue
		}

		if importID == "" {
			skipped = append(skipped, SkippedResourceInfo{
				Address: res.Address,
				Type:    res.Type,
				Reason:  "import ID is empty",
			})
			continue
		}

		block := GenerateImportBlock(res, importID)
		blocks = append(blocks, *block)
	}

	return blocks, skipped
}

// SortImportBlocks sorts import blocks by their Terraform address
func SortImportBlocks(blocks []ImportBlock) []ImportBlock {
	sort.Slice(blocks, func(i, j int) bool {
		return blocks[i].To < blocks[j].To
	})
	return blocks
}

// FormatImportBlocksAsFile formats all import blocks as a complete Terraform file
func FormatImportBlocksAsFile(blocks []ImportBlock) string {
	var output strings.Builder

	// Add header comment
	output.WriteString("# This file contains Terraform import blocks\n")
	output.WriteString("# Generated by tfimport-cli\n")
	output.WriteString("# Review and apply with: terraform apply -import\n\n")

	// Add each import block
	for _, block := range blocks {
		output.WriteString(FormatImportBlock(&block))
	}

	return output.String()
}

// FilterImportBlocks filters blocks by module or resource pattern
func FilterImportBlocksByModule(blocks []ImportBlock, moduleName string) []ImportBlock {
	var filtered []ImportBlock

	prefix := moduleName + "."
	for _, block := range blocks {
		if strings.HasPrefix(block.To, prefix) {
			filtered = append(filtered, block)
		}
	}

	return filtered
}

// FilterImportBlocksByResourceType filters blocks by resource type
func FilterImportBlocksByResourceType(blocks []ImportBlock, resourceType string) []ImportBlock {
	var filtered []ImportBlock

	for _, block := range blocks {
		// Extract resource type from address
		// e.g., "module.network.aws_vpc.main" -> "aws_vpc"
		parts := strings.Split(block.To, ".")
		if len(parts) >= 2 {
			// Last part is resource name, second-to-last is type
			if parts[len(parts)-2] == resourceType {
				filtered = append(filtered, block)
			}
		}
	}

	return filtered
}

// GroupImportBlocksByModule groups import blocks by their module
func GroupImportBlocksByModule(blocks []ImportBlock) map[string][]ImportBlock {
	groups := make(map[string][]ImportBlock)

	for _, block := range blocks {
		// Extract module from address
		parts := strings.Split(block.To, ".")
		var module string

		// Find the module path (everything before the resource type)
		if len(parts) > 1 && parts[0] == "module" {
			// Has module path
			module = strings.Join(parts[:len(parts)-2], ".")
		} else {
			// Root module
			module = "root"
		}

		groups[module] = append(groups[module], block)
	}

	return groups
}

// GroupImportBlocksByResourceType groups import blocks by their resource type
func GroupImportBlocksByResourceType(blocks []ImportBlock) map[string][]ImportBlock {
	groups := make(map[string][]ImportBlock)

	for _, block := range blocks {
		// Extract resource type from address
		parts := strings.Split(block.To, ".")
		if len(parts) >= 2 {
			// Second-to-last part is resource type
			resourceType := parts[len(parts)-2]
			groups[resourceType] = append(groups[resourceType], block)
		}
	}

	return groups
}

// CountImportBlocksByResourceType counts import blocks by resource type
func CountImportBlocksByResourceType(blocks []ImportBlock) map[string]int {
	counts := make(map[string]int)

	for _, block := range blocks {
		parts := strings.Split(block.To, ".")
		if len(parts) >= 2 {
			resourceType := parts[len(parts)-2]
			counts[resourceType]++
		}
	}

	return counts
}

// CountImportBlocksByModule counts import blocks by module
func CountImportBlocksByModule(blocks []ImportBlock) map[string]int {
	counts := make(map[string]int)

	for _, block := range blocks {
		parts := strings.Split(block.To, ".")
		var module string

		if len(parts) > 1 && parts[0] == "module" {
			module = strings.Join(parts[:len(parts)-2], ".")
		} else {
			module = "root"
		}

		counts[module]++
	}

	return counts
}
