package pkg

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// GenerateReport creates a summary report of an import generation run
func GenerateReport(scannedCount, matchedCount, generatedCount, skippedCount int, skippedDetails []SkippedResourceInfo) *Report {
	return &Report{
		ScannedCount:   scannedCount,
		MatchedCount:   matchedCount,
		GeneratedCount: generatedCount,
		SkippedCount:   skippedCount,
		SkippedDetails: skippedDetails,
	}
}

// GenerateReportFromState creates a report analyzing a Terraform state
func GenerateReportFromState(state *TerraformState, blocks []ImportBlock, skipped []SkippedResourceInfo) *Report {
	resourceCounts := ResourceCountByType(state)
	providers := GetProvidersInUse(state)

	// Count resources by type that are AWS and supported (skip data sources)
	supportedCount := 0
	unsupportedCount := 0
	managedCount := 0

	for _, sr := range state.Resources {
		// Skip data sources
		if sr.Mode == "data" {
			continue
		}
		managedCount++

		if strings.HasPrefix(sr.Type, "aws_") {
			if IsSupportedAWSResource(sr.Type) {
				supportedCount++
			} else {
				unsupportedCount++
			}
		} else {
			unsupportedCount++
		}
	}

	// Create module count map
	moduleCounts := make(map[string]int)
	for _, block := range blocks {
		parts := strings.Split(block.To, ".")
		var module string
		if len(parts) > 1 && parts[0] == "module" {
			module = strings.Join(parts[:len(parts)-2], ".")
		} else {
			module = "root"
		}
		moduleCounts[module]++
	}

	report := &Report{
		ScannedCount:     managedCount,
		MatchedCount:     len(blocks) + len(skipped),
		GeneratedCount:   len(blocks),
		SkippedCount:     len(skipped),
		SkippedDetails:   skipped,
		ResourceTypes:    resourceCounts,
		Modules:          moduleCounts,
		UnsupportedCount: unsupportedCount,
		Providers:        providers,
	}

	return report
}

// FormatReportAsJSON converts a report to JSON format
func FormatReportAsJSON(report *Report) (string, error) {
	data, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		return "", fmt.Errorf("failed to marshal report: %w", err)
	}

	return string(data), nil
}

// FormatReportAsConsole formats a report for console output
func FormatReportAsConsole(report *Report) string {
	var output strings.Builder

	output.WriteString("\n=== Import Generation Report ===\n\n")

	output.WriteString("Summary:\n")
	output.WriteString(fmt.Sprintf("  Scanned:    %d\n", report.ScannedCount))
	output.WriteString(fmt.Sprintf("  Matched:    %d\n", report.MatchedCount))
	output.WriteString(fmt.Sprintf("  Generated:  %d\n", report.GeneratedCount))
	output.WriteString(fmt.Sprintf("  Skipped:    %d\n", report.SkippedCount))

	if report.UnsupportedCount > 0 {
		output.WriteString(fmt.Sprintf("  Unsupported: %d\n", report.UnsupportedCount))
	}

	output.WriteString("\n")

	// Provider information
	if len(report.Providers) > 0 {
		output.WriteString("Providers:\n")
		sort.Strings(report.Providers)
		for _, p := range report.Providers {
			output.WriteString(fmt.Sprintf("  - %s\n", p))
		}
		output.WriteString("\n")
	}

	// Resource type breakdown
	if len(report.ResourceTypes) > 0 {
		output.WriteString("Resource Types (All):\n")

		// Sort types by count (descending)
		type typeCount struct {
			name  string
			count int
		}
		var types []typeCount
		for name, count := range report.ResourceTypes {
			types = append(types, typeCount{name, count})
		}
		sort.Slice(types, func(i, j int) bool {
			if types[i].count != types[j].count {
				return types[i].count > types[j].count
			}
			return types[i].name < types[j].name
		})

		for _, t := range types {
			supported := ""
			if IsSupportedAWSResource(t.name) {
				supported = " [supported]"
			}
			output.WriteString(fmt.Sprintf("  %s: %d%s\n", t.name, t.count, supported))
		}

		output.WriteString("\n")
	}

	// Module breakdown
	if len(report.Modules) > 0 {
		output.WriteString("Generated by Module:\n")

		// Sort modules
		var modules []string
		for m := range report.Modules {
			modules = append(modules, m)
		}
		sort.Strings(modules)

		for _, m := range modules {
			count := report.Modules[m]
			if m == "root" {
				output.WriteString(fmt.Sprintf("  (root): %d\n", count))
			} else {
				output.WriteString(fmt.Sprintf("  %s: %d\n", m, count))
			}
		}

		output.WriteString("\n")
	}

	// Skipped resources with reasons
	if len(report.SkippedDetails) > 0 {
		output.WriteString("Skipped Resources:\n")

		// Group by reason
		reasonMap := make(map[string][]string)
		for _, skipped := range report.SkippedDetails {
			reasonMap[skipped.Reason] = append(reasonMap[skipped.Reason], skipped.Address)
		}

		// Sort reasons
		var reasons []string
		for r := range reasonMap {
			reasons = append(reasons, r)
		}
		sort.Strings(reasons)

		for _, reason := range reasons {
			addresses := reasonMap[reason]
			output.WriteString(fmt.Sprintf("  %s (%d):\n", reason, len(addresses)))

			// Show first 3 addresses as examples
			for i, addr := range addresses {
				if i >= 3 {
					output.WriteString(fmt.Sprintf("    ... and %d more\n", len(addresses)-3))
					break
				}
				output.WriteString(fmt.Sprintf("    - %s\n", addr))
			}
		}

		output.WriteString("\n")
	}

	return output.String()
}

// GenerateAnalysisReport creates a report for the analyze command
func GenerateAnalysisReport(state *TerraformState) *Report {
	resourceCounts := ResourceCountByType(state)
	providers := GetProvidersInUse(state)

	// Count resources by type (skip data sources)
	supportedCount := 0
	unsupportedCount := 0
	managedCount := 0

	for _, sr := range state.Resources {
		// Skip data sources
		if sr.Mode == "data" {
			continue
		}
		managedCount++

		if strings.HasPrefix(sr.Type, "aws_") {
			if IsSupportedAWSResource(sr.Type) {
				supportedCount++
			} else {
				unsupportedCount++
			}
		} else {
			unsupportedCount++
		}
	}

	// Create module count map (skip data sources)
	moduleCounts := make(map[string]int)
	for _, sr := range state.Resources {
		// Skip data sources
		if sr.Mode == "data" {
			continue
		}
		if sr.Module != "" {
			moduleCounts[sr.Module]++
		} else {
			moduleCounts["root"]++
		}
	}

	report := &Report{
		ScannedCount:     managedCount,
		ResourceTypes:    resourceCounts,
		Modules:          moduleCounts,
		UnsupportedCount: unsupportedCount,
		Providers:        providers,
	}

	return report
}

// FormatAnalysisReportAsConsole formats an analysis report for console output
func FormatAnalysisReportAsConsole(report *Report) string {
	var output strings.Builder

	output.WriteString("\n=== State Analysis Report ===\n\n")

	output.WriteString("Summary:\n")
	output.WriteString(fmt.Sprintf("  Total Resources: %d\n", report.ScannedCount))

	if report.UnsupportedCount > 0 {
		supported := report.ScannedCount - report.UnsupportedCount
		output.WriteString(fmt.Sprintf("  Managed (AWS): %d\n", supported))
		output.WriteString(fmt.Sprintf("  Other/Unsupported: %d\n", report.UnsupportedCount))
	}

	output.WriteString("\n")

	// Providers
	if len(report.Providers) > 0 {
		output.WriteString("Providers:\n")
		sort.Strings(report.Providers)
		for _, p := range report.Providers {
			output.WriteString(fmt.Sprintf("  - %s\n", p))
		}
		output.WriteString("\n")
	}

	// Top resource types
	if len(report.ResourceTypes) > 0 {
		output.WriteString("Top Resource Types:\n")

		type typeCount struct {
			name  string
			count int
		}
		var types []typeCount
		for name, count := range report.ResourceTypes {
			types = append(types, typeCount{name, count})
		}

		// Sort by count descending
		sort.Slice(types, func(i, j int) bool {
			if types[i].count != types[j].count {
				return types[i].count > types[j].count
			}
			return types[i].name < types[j].name
		})

		// Show top 10
		limit := 10
		if len(types) < limit {
			limit = len(types)
		}

		for i := 0; i < limit; i++ {
			t := types[i]
			supported := ""
			if IsSupportedAWSResource(t.name) {
				supported = " [supported]"
			}
			output.WriteString(fmt.Sprintf("  %s: %d%s\n", t.name, t.count, supported))
		}

		if len(types) > limit {
			output.WriteString(fmt.Sprintf("  ... and %d more\n", len(types)-limit))
		}

		output.WriteString("\n")
	}

	// Modules
	if len(report.Modules) > 0 {
		output.WriteString("Modules:\n")

		var modules []string
		for m := range report.Modules {
			modules = append(modules, m)
		}
		sort.Strings(modules)

		for _, m := range modules {
			count := report.Modules[m]
			if m == "root" {
				output.WriteString(fmt.Sprintf("  (root): %d resources\n", count))
			} else {
				output.WriteString(fmt.Sprintf("  %s: %d resources\n", m, count))
			}
		}

		output.WriteString("\n")
	}

	return output.String()
}
